//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NovacMasterProgram.rc
//
#define ID_CONNECT_TO                   0
#define ID_DIRECT_SERIAL_LINK           0
#define ID_FTP_SERVER                   0
#define ID_DIRECTSERIALLINK             0
#define IDR_MANIFEST                    1
#define ERROR_REFERENCEFILE_NOT_FOUND   1
#define ERROR_EVALUATION_WILL_NOT_BE_CORRECT 2
#define MSG_PLEASE_CHECK_EVALCONFIG_AND_RESTART 3
#define MSG_REFERENCES_NOT_FOUND        4
#define ERROR_COULD_NOT_FIND_REFERENCE_FILE 5
#define MSG_SPECTROMETERS_CONFIGURED    6
#define IDD_CONFIGURATION_GLOBAL        9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_NOVACMASTERPROGRAM_FORM     101
#define IDD_ADVANCEDFTPUPLOADSETTINGS   103
#define IDD_CONFIGURE_COM_PORT          106
#define IDD_REEVAL_SCANFILES            107
#define IDD_COLUMN_HISTORY_DLG          108
#define IDR_MAINFRAME                   128
#define IDR_NovacMasterProgTYPE         129
#define ERROR_WIND_NOT_FOUND            129
#define ID_VIEW_LANGUAGE                129
#define MSG_READING                     130
#define ERROR_EVALCONFIG_NOT_FOUND      131
#define ERROR_EVALCONFIG_NOT_FOUND_PLEASE_CHOOSE 132
#define ID_ESP_SETLANGUAGE              132
#define MSG_READING_DONE                133
#define ID_SETLANGUAGE_ENGLISH          133
#define ID_SETLANGUAGE_ESPA             134
#define ID_CONFIGURATION_LANGUAGE       134
#define ERROR_COULD_NOT_OPEN_EVALCONFIG 134
#define ID_SET_LANGUAGE_ENGLISH         135
#define ID_SET_LANGUAGE_ESPA            136
#define RECIEVED_NEW_SCAN_FROM          137
#define ID_SHOW_CONFIGURATION_EVALUATION 137
#define MSG_ERROR                       138
#define MSG_YOU_HAVE_TO_RESTART         139
#define ID_CONTROL_CONNECTTO            139
#define MSG_NO_CHANGES_WILL_BE_SAVED    140
#define IDB_YELLOW_LIGHT                140
#define ID_CONTROL_CONNECTTO140         140
#define IDB_GREEN_LIGHT                 141
#define ID_CONNECTTO_DIRECTSERIALLINK   141
#define MSG_PLEASE_PRESS_START          141
#define IDB_RED_LIGHT1                  142
#define IDB_RED_LIGHT                   142
#define ID_CONFIGURATION_COMMUNICATION  142
#define MSG_DOWNLOADING_UPLOADPAK       142
#define ID_COMMUNICATION_COMPORT        143
#define MSG_COULD_NOT_START_TXZM        143
#define IDD_CONFIGURATION_DIALOG        144
#define MSG_DOWNLOAD_FINISHED           144
#define ID_CONFIGURATION_CONFIGURATION  145
#define IDD_CONFIGURATION_SCANNER       145
#define MSG_CORRUPT_UPLOADPAK_WILL_TRY_AGAIN 146
#define MSG_DOWNLOAD_NOT_COMPLETE       147
#define IDD_QUERY_SELECTION_DIALOG      148
#define MSG_UPLOADPAK_NOT_FOUND         148
#define ID_CONTROL_START149             149
#define MSG_UPLOADPAK_SIZE_IS_OK        149
#define IDR_MENU1                       149
#define IDR_MEASUREMENT_MENU            149
#define MSG_PROGRAM_STARTED_SUCESSFULLY 150
#define ID__INSERTROW                   150
#define MSG_PROGRAM_ALREADY_RUNNING     151
#define ID__DELETEROW                   151
#define ID_ANALYSIS_FLUX                152
#define ID_ANALYSIS_FLUX153             153
#define ID_CONFIGURATION_REMOTE         153
#define AXIS_COLUMN                     154
#define ID__RENAME                      155
#define AXIS_FLUX                       155
#define ID__REMOVE                      156
#define AXIS_ANGLE                      156
#define ID__ADD                         157
#define AXIS_INTENSITY                  157
#define IDD_POSTFLUX_DLG                158
#define AXIS_TIMEOFDAY                  158
#define IDB_BMP_NEXT                    159
#define IDD_REEVAL_WINDOW               159
#define AXIS_SATURATION                 159
#define IDB_BMP_PREV                    160
#define IDD_REEVAL_FINAL                160
#define AXIS_CHANNEL                    160
#define ID_ANALYSIS_REEVALUATE          161
#define IDD_REEVAL_MISC                 161
#define ID_ANALYSIS_REEVALUATE162       162
#define IDD_EXPORT_SPECTRA              162
#define AXIS_LATITUDE                   162
#define IDR_REEVAL_CONTEXTMENU          163
#define IDD_EXPORT_EVALLOG              163
#define AXIS_LONGITUDE                  163
#define ID__INSERT                      164
#define STR_SITE                        164
#define ID__DELETE                      165
#define STR_COMPASSDIRECTION            165
#define ID_ANALYSIS_TESTEVALUATION      166
#define IDR_POSTFLUXDLG_MENU            167
#define STR_LATITUDE                    167
#define ID_VIEW_PEAKINTENSITY           168
#define STR_LONGITUDE                   168
#define ID_VIEW_COLUMNERROR             169
#define STR_SCANNER                     169
#define ID_VIEW_DELTA                   170
#define STR_STARTTIME                   170
#define ID_FILE                         171
#define STR_STOPTIME                    171
#define ID_VIEW_NEXTSCAN                172
#define STR_EXPTIME                     172
#define ID_VIEW_PREVIOUSSCAN            173
#define STR_NUMSPECTRA                  173
#define ID_CALCULATE_FLUX               174
#define STR_CALCWINDDIRECTION           174
#define ID_FILE_OPENEVALUATIONLOG       175
#define STR_FLAT                        175
#define ID_FILE_EXPORT                  176
#define ID_FILE_EXPORT177               177
#define STR_CONE                        177
#define AXIS_LOCALTIME                  178
#define IDD_FILETRANSFER_DLG            179
#define ERROR_COULD_NOT_OPEN_FTPLOGIN_CONFIG 179
#define ID_CONFIGURATION_FILETRANSFER   180
#define ID_CONFIGURACI_FILETRANSFER     181
#define AXIS_UTCTIME                    181
#define IDD_VIEW_SCANNERSTATUS          182
#define IDD_VIEW_OVERVIEW               184
#define IDD_CONFIGURE_EVALUATION        185
#define IDD_CONFIGURE_LOCATION          186
#define ID_FILE_IMPORT                  187
#define IDD_IMPORT_SPECTRA              187
#define ID_VIEW_CHISQUARE               188
#define IDD_REFERENCE_PROPERTIES_DLG    189
#define ID__PROPERTIES                  190
#define IDB_DAT                         191
#define IDB_PAK                         192
#define IDB_EXE                         193
#define IDB_DISK                        194
#define IDB_TXT                         195
#define IDR_FILETREE_POP_MENU           196
#define ID_FILETREE_DOWNLOAD            197
#define ID_FILETREE_VIEWFILE            198
#define ID_FILETREE_DELETE              199
#define ID__INSERT203                   203
#define IDR_FITWINDOWLIST_MENU          204
#define ID_Menu                         205
#define ID__INSERTFITWINDOW             206
#define ID__REMOVEWINDOW                207
#define ID__LOADWINDOWFROMFILE          208
#define ID__SAVEWINDOWTOFILE            209
#define ID__RENAMEWINDOW                210
#define ID_VIEW_FITINTENSITY            211
#define IDD_GEOMETRY_DIALOG             212
#define ID_ANALYSIS_SETUP               213
#define IDD_POST_WINDSPEED_DLG          215
#define ID_ANALYSIS_WIND                216
#define IDD_PAKFILES_SPLIT              216
#define ID_ANALYSIS_WIND217             217
#define IDD_CONFIGURE_WIND              217
#define ID_ANALYSIS_SETUP218            218
#define ID_FILE_SPLITPAKFILE            219
#define ID_FILE_SPLITMERGE              219
#define ID_FILE_SPLIT                   220
#define IDD_WIND_STARTDLG               221
#define ID_CONTROL_MAKEWINDMEASUREMENT  222
#define IDD_DATA_BROWSE_DLG             222
#define ID_CALCULATE_FLUXFORALLSCANSINTHEPLUME 223
#define IDD_PAKFILES_MERGE              223
#define ID_CALCULATE_WINDDIRECTION      224
#define IDD_CONFIGURE_DARK              224
#define ID_Menu227                      227
#define IDR_BROWSE_DATA_MENU            229
#define ID_FILE_OPENEVALUATIONLOG230    230
#define IDR_MAINFRAME1                  230
#define ID_Menu231                      231
#define ID_FILE_QUIT                    232
#define ID_ANALYSIS_BROWSEMEASUREDDATA  233
#define ID_Menu234                      234
#define ID_FILE_CHECKPAKFILE            237
#define IDD_CHECK_PAKFILE               238
#define IDD_VIEW_WIND_OVERVIEW          239
#define IDB_BITMAP1                     240
#define IDB_FOLDER                      240
#define IDD_VIEW_INSTRUMENT_OVERVIEW    240
#define IDB_BITMAP2                     242
#define IDB_BATTERY                     242
#define ID_MENU_VIEW_INSTRUMENTTAB      243
#define IDD_CONFIGURATION_ADVANCED_FTP_UPLOAD 244
#define IDD_VIEW_INSTRUMENT_OVERVIEW1   245
#define ID_VIEW_UNITOFFLUX              246
#define ID_UNITOFFLUX_KG                247
#define ID_UNITOFFLUX_TON               248
#define ID_FILE_SAVEEVALUATIONLOG       249
#define ID_ARCHIVO_ID                   250
#define IDD_FLUXERROR_DIALOG            251
#define ID_FILE_IMPORTWINDFIELD         252
#define IDD_DARK_SETTINGS_DLG           254
#define IDB_BMP_SAVE                    256
#define IDB_BMP_OPEN                    257
#define IDR_MENU_REEVALUATION           258
#define ID_FILE_LOADSCAN                259
#define ID_FILE_LOADFITWINDOWS          260
#define ID_FILE_SAVECURRENTFITWINDOWS   261
#define ID_FILE_LOADMISC                262
#define ID_FILE_CLOSE263                263
#define ID_FILE_LOADMISC2               263
#define ID_FILE_SAVEMISC                264
#define IDR_REEVAL_SCAN_CONTEXTMENU     265
#define ID__INSERT266                   266
#define ID__REMOVESELECTED              267
#define IDI_NOVACICON                   274
#define IDR_GEOMETRYDLG_MENU            275
#define ID_FILE_SAVEGRAPHASIMAGE        276
#define ID_ANALYSIS_CALCULATEPLUMEHEIGHTSWINDDIRECTIONS 277
#define IDD_SUMMARIZE_POSTFLUX          278
#define ID_ANALYSIS_SUMMARIZEFLUXDATA   279
#define ID_Menu280                      280
#define IDD_VIEW_INSTRUMENT_OVERVIEW3   280
#define ID_CONTROL_SELECTSCANSTOEVALUATE 281
#define ID_SELECTSCAN_BROWSEDIR         282
#define ID_SELECTSCANSTOEVALUATE_BROWSEFILES 283
#define ID_ANALYSIS_CALCULATE_PH_WD_REALTIMELOGS 284
#define ID_ANALYSIS_6                   285
#define IDD_QUERY_STRING_DIALOG         286
#define IDD_CONFIGURE_VII_ADVANCED      287
#define IDD_STARTDLG_COMPOSITIONMEAS    288
#define ID_CONTROL_MAKECOMPOSITIONMEASUREMENT 289
#define ID_CONTROL_MAKECOMPOSITIONMEASUREMENT290 290
#define ID_FILETREE_ENTERFOLDER         291
#define ID_VIEW_UNITOFCOLUMNS           292
#define ID_UNITOFCOLUMNS_PPMM           293
#define ID_UNITOFCOLUMNS_MOLEC_CM2      294
#define IDR_MENU2                       295
#define IDR_MENU_SHOWFIT_CONTEXT        295
#define ID__SAVEASASCII                 296
#define ID__SAVEASBITMAP                297
#define IDD_REFERENCE_PLOT_DLG          299
#define IDD_ANALYSIS_COLUMN_HISTORY_DLG 300
#define IDC_STATIC_VERSIONNUMBER        1000
#define IDC_STATIC_COPYRIGHT            1001
#define IDC_BUTTON_TEST                 1002
#define IDC_STATIC_COPYRIGHT2           1002
#define IDC_STATIC_CREDITS              1002
#define IDC_SPECTROMETER_LIST           1003
#define IDC_EDIT_VOLCANO                1005
#define IDC_EDIT_SITE                   1006
#define IDC_EDIT_OBSERVATORY            1007
#define IDC_EDIT_COMPASSDIRECTION       1008
#define IDC_EDIT_MINCOL                 1008
#define IDC_EDIT_SYSTEMTILT             1009
#define IDC_EDIT_MAXCOL                 1009
#define IDC_EDIT_FITLOW                 1010
#define IDC_EDIT_FITHIGH                1011
#define IDC_EDIT_OUTPUTDIR              1012
#define IDC_STATIC_REFERENCEFILES       1015
#define IDC_SYSTEM_TAB_CONTROL          1016
#define IDC_STATIC_COLUMN               1017
#define IDC_STATIC_FLUX                 1018
#define IDC_STATIC_COLUMNERROR          1018
#define IDC_STATUS_LIGHT                1019
#define IDC_COMBO_SCANNING_INSTRUMENT   1020
#define IDC_COMBO2                      1021
#define IDC_GAS_COMBO                   1021
#define IDC_COMBO_SPECTROMETERMODEL     1021
#define IDC_STATIC_FRAME                1023
#define IDC_EDIT_OUTPUT_DIRECTORY       1025
#define IDC_BUTTON_BROWSE_OUTPUTPATH    1026
#define IDC_BUTTON_BROWSE_OUTPUTPATH2   1027
#define IDC_BUTTON_BROWSE_WINDFIELDFILE 1027
#define IDC_SCANNER_LIST                1028
#define IDC_BUTTON_ADD_SCANNER          1029
#define IDC_BUTTON_REMOVE_SCANNER       1030
#define IDC_STRING_EDIT                 1030
#define IDC_BUTTON_ADDREFERENCE         1031
#define IDC_SELECTION_COMBO             1032
#define IDC_BUTTON_REMOVEREFERENCE      1033
#define IDC_COMPORT_COMBO               1034
#define IDC_BUTTON_REMOVEREFERENCE2     1034
#define IDC_BUTTON_PROPERTIES           1034
#define IDC_BAUDRATE_COMBO              1035
#define IDC_BUTTON_VIEW                 1035
#define IDC_HANDSHAKE_COMBO             1036
#define IDC_TIMEOUT_EDIT                1037
#define IDC_INTERVAL_HR                 1038
#define IDC_INTERVAL_MIN                1039
#define IDC_BUTTON_SET_WINDFIELD        1039
#define IDC_INTERVAL_SEC                1040
#define IDC_EDIT_WINDDIRECTION          1040
#define IDC_EDIT_WINDSPEED              1041
#define IDC_ELEVATIONANGLELIST          1041
#define IDC_EDIT_WINDSPEED2             1042
#define IDC_EDIT_PLUMEHEIGHT            1042
#define IDC_FLUX_PLOT                   1043
#define IDC_EDIT_WINDDIRECTION2         1043
#define IDC_BUTTON_SET_WINDFIELD2       1043
#define IDC_STATUS_MESSAGE_LIST         1044
#define IDC_COLUMN_PLOT                 1044
#define IDC_SCANNER_TREE                1045
#define IDC_STARTUP_MANUAL              1046
#define IDC_STARTUP_AUTOMATIC           1047
#define IDC_CONFINFO_SITE               1047
#define IDC_CONFINFO_COMPASS            1048
#define IDC_CONFINFO_LATITUDE           1049
#define IDC_CONFINFO_LONGITUDE          1050
#define IDC_STATIC_TIMEOUT              1051
#define IDC_CONFINFO_CONEORFLAT         1051
#define IDC_STATIC_CONNECTION_INTERVAL  1052
#define IDC_SCANINFO_STARTTIME          1052
#define IDC_CONFINFO_LONGITUDE3         1053
#define IDC_SCANINFO_STOPTIME           1053
#define IDC_SCANINFO_EXPTIME            1054
#define IDC_SCANINFO_EXPTIME2           1055
#define IDC_SCANINFO_NSPEC              1055
#define IDC_SCANINFO_NSPEC2             1056
#define IDC_SCANINFO_CALC_WD            1056
#define IDC_MOTOR_ANGLECOMP             1057
#define IDC_SCANINFO_DATE               1057
#define IDC_CONFINFO_LATITUDE2          1058
#define IDC_BUTTON1                     1063
#define IDC_BTN_BROWSE_SCANFILES        1063
#define IDC_BTN_BROWSESCANFILE          1063
#define IDC_REEVAL_DOEVAL               1063
#define IDC_BTN_BROWSE_EVALLOG          1063
#define IDC_UPLOAD_BTN                  1063
#define IDC_BUTTON_INSERT_REFERENCE     1063
#define IDC_BUTTON_BROWSE_REFERENCE     1063
#define IDC_BTN_BROWSEEVALLOG           1063
#define IDC_BTN_BROWSEPAKFILES          1063
#define IDC_BTN_BROWSESKY               1063
#define IDC_BTN_CALCULATE_WINDSPEED     1063
#define IDC_BUTTON_BROWSE_OFFSET        1063
#define IDC_OPEN_PAKFILE                1063
#define IDC_BUTTON_ADVANCED_FTP         1063
#define IDC_BUTTON_SEARCH               1063
#define IDC_BUTTON2                     1064
#define IDC_BTN_CALC_FLUX               1064
#define IDC_REEVAL_CANCEL               1064
#define IDC_BROWSE_PAKFILE_BTN          1064
#define IDC_DOWNLOAD_BTN                1064
#define IDC_BUTTON_REMOVE_REFERENCE     1064
#define IDC_BROWSE_SERIES1              1064
#define IDC_BTN_BROWSEOUTPUTDIR         1064
#define IDC_BTN_BROWSEEVALLOG2          1064
#define IDC_BUTTON_BROWSE_DARKCURRENT   1064
#define IDC_BTN_BROWSEOFFSETSPEC        1064
#define IDC_BUTTON_DARK_SETTINGS        1064
#define IDC_BROWSE_EXPORTDIR            1065
#define IDC_BUTTON_REFERENCE_PROEPERTIES 1065
#define IDC_BROWSE_SERIES2              1065
#define IDC_BUTTON_BROWSE_OFFSET2       1065
#define IDC_BTN_BROWSESKY3              1065
#define IDC_BTN_BROWSEDARKCURRENTSPEC   1065
#define IDC_BTN_BROWSEEVALLOG3          1065
#define IDC_BUTTON_BROWSE_DARKCURRENT2  1066
#define IDC_BTN_BROWSEEVALLOG4          1066
#define IDC_BUTTON_REFERENCE_VIEW       1066
#define IDC_PF_WINDSPEED                1069
#define IDC_PF_WINDDIRECTION            1070
#define IDC_PF_COMPASS                  1071
#define IDC_PF_PLUMEHEIGHT              1072
#define IDC_EDIT2                       1073
#define IDC_EVALUATION_LOG_EDIT         1073
#define IDC_EDIT_SCANANGLES             1073
#define IDC_EDIT_SHIFT_FIX              1073
#define IDC_FILE_CONTENT                1073
#define IDC_EDIT_LP_ITERATIONS          1073
#define IDC_EDIT_OUTPUTDIRECTORY        1073
#define IDC_EDIT_LOCALDIRECTORY         1073
#define IDC_EDIT_OFFSETSPEC             1073
#define IDC_EDIT_SKYINDEX               1073
#define IDC_EDIT_ANGLE                  1073
#define IDC_EDIT_MOTORSTEPSCOMPENSATION1 1073
#define IDC_FTP_HOSTNAME                1073
#define IDC_STATUSBAR                   1074
#define IDC_EDIT_SQUEEZE_FIX            1074
#define IDC_EDIT_SHIFT_MAX              1074
#define IDC_EDIT_DARKCURSPEC            1074
#define IDC_EDIT_DISTANCE               1074
#define IDC_EDIT_MOTORSTEPSCOMPENSATION2 1074
#define IDC_EDIT_FLUX                   1075
#define IDC_EDIT_SHIFT_LINK             1075
#define IDC_EDIT_TESTLENGTH             1075
#define IDC_EDIT_MOTORSTEPSCOMP3        1075
#define IDC_EDIT_SWITCHRANGE            1075
#define IDC_BTN_NEXT                    1076
#define IDC_EDIT_SQUEEZE_LINK           1076
#define IDC_EDIT_TESTLENGTH2            1076
#define IDC_PF_CONEANGLE                1076
#define IDC_EDIT_STEPSPERROUND1         1076
#define IDC_BTN_PREV                    1077
#define IDC_PF_CONEANGLE2               1077
#define IDC_PF_INSTRUMENTTYPE           1077
#define IDC_EDIT_STEPSPERROUND2         1077
#define IDC_COMBO1                      1078
#define IDC_COMBO_FLUXUNIT              1078
#define IDC_REMOTE_FILE_COMBO           1078
#define IDC_COMBO_VOLCANO               1078
#define IDC_DISKCOMBO                   1078
#define IDC_COMBO_IMAGEFORMAT           1078
#define IDC_COMBO_OFFSET                1078
#define IDC_SLEEPHR                     1079
#define IDC_COMBO_DARKCURRENT           1079
#define IDC_COMBO_VOLCANO2              1079
#define IDC_COMBO_INSTRUMENTTYPE        1079
#define IDC_COMBO_DARKCURRENT2          1079
#define IDC_PF_COMPASS2                 1079
#define IDC_PF_TILT                     1079
#define IDC_SLEEPMIN                    1080
#define IDC_COMBO_OBSERVATORY           1080
#define IDC_SLEEPSEC                    1081
#define IDC_SCANFILE_LIST               1081
#define IDC_COMBO_ELECTRONICS           1081
#define IDC_WAKEHR                      1082
#define IDC_WAKEMIN                     1083
#define IDC_SPECGRAPH_FRAME             1083
#define IDC_EDIT7                       1084
#define IDC_WAKESEC                     1084
#define IDC_NUMSPEC_LABEL               1084
#define IDC_LBL_DATE                    1085
#define IDC_LBL_STARTTIME               1086
#define IDC_LBL_STOPTIME                1087
#define IDC_LBL_EXPTIME                 1088
#define IDC_LBL_NUMSPEC                 1089
#define IDC_LBL_MOTORPOS                1090
#define IDC_LBL_CONEORFLAT              1091
#define IDC_LBL_DEVICE                  1092
#define IDC_SPEC_SPIN                   1093
#define IDC_FITWINDOW_LIST              1094
#define IDC_EDIT_POLYNOM                1097
#define IDC_FIT_HP_DIV                  1098
#define IDC_REF_STATIC                  1099
#define IDC_CHECK_UV                    1100
#define IDC_FIT_HP_SUB                  1101
#define IDC_FIT_POLY                    1102
#define IDC_RADIO_SHOWFIT               1102
#define IDC_CHECK_INTERLACED            1103
#define IDC_RADIO_SHOW_RESIDUAL         1103
#define IDC_CHECK_SHIFT_SKY             1103
#define IDC_SPECIE_LIST                 1104
#define IDC_LBL_SHOWING                 1105
#define IDC_TOTALFIT_FRAME              1106
#define IDC_REFFIT_FRAME                1107
#define IDC_IGNORE_DARK                 1108
#define IDC_IGNORE_SATURATED            1109
#define IDC_IGNORE_INTENSITY            1110
#define IDC_EDIT_IGNORE_INTENSITY       1111
#define IDC_EDIT_IGNORE_CHANNEL         1112
#define IDC_PROGRESSBAR                 1112
#define IDC_REEVAL_STATUSBAR            1113
#define IDC_UPPER_IGNORE_INTENSITY      1113
#define IDC_REEVAL_LBL_COLUMN           1114
#define IDC_EDIT_UPPER_IGNORE_INTENSITY 1114
#define IDC_REEVAL_LBL_SHIFT            1115
#define IDC_EDIT_UPPER_IGNORE_CHANNEL   1115
#define IDC_REEVAL_LBL_SQUEEZE          1116
#define IDC_IGNORE_NOTHING              1116
#define IDC_CHECK1                      1117
#define IDC_REEVAL_CHECK_PAUSE          1117
#define IDC_CHECK_FIND_OPTIMAL          1117
#define IDC_CHECK_SCANANGLES            1117
#define IDC_UPPER_IGNORE_NOTHING        1117
#define IDC_CHECK_DOWINDSPEED           1117
#define IDC_CHECK_SHOW_VOLCANO          1117
#define IDC_CHECK_PUBLISH               1117
#define IDC_CHECK_INCLUDE_SUBDIRS       1117
#define IDC_CHECK_ENABLE_REALTIME_CFG   1117
#define IDC_CHECK_PLOT_COLUMN_ONLY      1117
#define IDC_CHECK_PLOT_COLUMN           1117
#define IDC_EDIT1                       1118
#define IDC_FTPUSER                     1118
#define IDC_EDIT_SELECTEDPOINTS         1118
#define IDC_REEVAL_LBL_DELTA            1118
#define IDC_EDIT_EVALUATIONLOGPATH      1118
#define IDC_EDIT_RADIOID                1118
#define IDC_EDIT_SPECPERSCAN            1118
#define IDC_EDIT_SERIALNUMBER           1118
#define IDC_EDIT_SPECIE                 1118
#define IDC_LOCALFILEEDIT               1118
#define IDC_EDIT_EVALLOG1               1118
#define IDC_EDIT_USER_SKY               1118
#define IDC_EDIT_MOTORPOSITION          1118
#define IDC_EDIT_OFFSETSPECTRUM         1118
#define IDC_EDIT_START_HR               1118
#define IDC_EDIT_GEOMERROR              1118
#define IDC_EDIT_MERGENUM               1118
#define IDC_EDIT_DIRECTORY              1118
#define IDC_EDIT_WD_TOLERANCE           1118
#define IDC_EDIT_PLUMECENTRE            1118
#define IDC_EDIT_SOLARSPECTRUMPATH      1118
#define IDC_FTPIP                       1119
#define IDC_EDIT_EXPORTDIR              1119
#define IDC_REEVAL_LBL_DELTA2           1119
#define IDC_REEVAL_LBL_CHISQUARE        1119
#define IDC_EDIT_PATH                   1119
#define IDC_EDIT_EVALLOG2               1119
#define IDC_EDIT                        1119
#define IDC_EDIT_SUM1                   1119
#define IDC_EDIT_DARKCURRENT_SPECTRUM   1119
#define IDC_EDIT_START_MIN              1119
#define IDC_EDIT_SPECERROR              1119
#define IDC_IGNORE_NOTHING2             1119
#define IDC_EDIT_PLUMEDGE_LOW           1119
#define IDC_CHECK_PLOT_COLUMN_HISTORY   1119
#define IDC_FTPPASS                     1120
#define IDC_FTP_USERNAME                1120
#define IDC_EDIT_REPETITIONS            1120
#define IDC_PROGRESSBAR2                1120
#define IDC_EDIT_OFFSETSPECTRUM2        1120
#define IDC_EDIT_START_SEC              1120
#define IDC_EDIT_SCATTERINGERROR        1120
#define IDC_EDIT_EVALLOG3               1120
#define IDC_EDIT_PLUMEDGE_HIGH          1120
#define IDC_FTP_PASSWORD                1121
#define IDC_EDIT_STEPSPERROUND          1121
#define IDC_REEVAL_STATUSBAR2           1121
#define IDC_EDIT_DARKCURRENT_SPECTRUM2  1121
#define IDC_EDIT_STOP_HR                1121
#define IDC_EDIT6                       1121
#define IDC_EDIT_WINDERROR              1121
#define IDC_CHECK_SHOW_VOLCANO2         1121
#define IDC_CHECK_VARYING_SIZE          1121
#define IDC_CHECK_WINDFIELDFILE_ENABLED 1121
#define IDC_EDIT_                       1122
#define IDC_EDIT_MOTORSTEPSCOMP         1122
#define IDC_EDIT_STOP_MIN               1122
#define IDC_EDIT_DARKCURRENT_SPECTRUM3  1122
#define IDC_EDIT_USER_SUPPLIED_DARK_SPECTRUM 1122
#define IDC_EDIT_EVALLOG4               1122
#define IDC_EDIT_PERCENT                1123
#define IDC_EDIT9                       1123
#define IDC_EDIT_STOP_SEC               1123
#define IDC_EDIT_COMPASSDIR             1123
#define IDC_EDIT_COMPASS                1124
#define IDC_EDIT_INTERVAL               1125
#define IDC_EDIT_DURATION               1126
#define IDC_EDIT_MAXANGLE               1127
#define IDC_SCANGRAPH_FRAME             1128
#define IDC_SCAN_SPINBTN                1129
#define IDC_FLUXGRAPH_FRAME             1130
#define IDC_INTENSITY_SLIDER            1131
#define IDC_INTENSITY_SLIDER2           1132
#define IDC_OFFSET_SLIDER               1132
#define IDC_EDIT_STABLEPERIOD           1133
#define IDC_BTN_DELETEPOINTS            1134
#define IDC_EDIT_MINPEAKCOLUMN          1135
#define IDC_OFFSET_LABEL                1136
#define IDC_COMMSTATUS                  1137
#define IDC_EDIT_OFFSET                 1138
#define IDC_RADIO_CALCULATE_OFFSET      1139
#define IDC_RADIO_USETHIS_OFFSET        1140
#define IDC_RADIO_SKYSPECTRUM_FIRST     1140
#define IDC_RADIO_SKYSPECTRUM_AVERAGE   1141
#define IDC_EDIT_OFFSET_DELTA           1141
#define IDC_EDIT_OFFSET_INTENSITY_ABOVE 1142
#define IDC_RADIO_SKYSPECTRUM_USER      1142
#define IDC_EDIT_OFFSET_INTENSITY_BELOW 1143
#define IDC_RADIO_SKYSPECTRUM_INDEX     1143
#define IDC_RADIO_EXPORTFORMAT_STD      1144
#define IDC_RADIO_CALCULATEOFFSET_2     1144
#define IDC_EXPORT_SPECTRA_BTN          1145
#define IDC_STATIC_PAKFILES             1146
#define IDC_EDIT_OFFSET_CHI2            1146
#define IDC_BROWSE_EVALLOG_BTN          1147
#define IDC_BROWSE_EXPORTFILE           1148
#define IDC_EDIT_EXPORTFILE             1149
#define IDC_EXPORT_LOG_BTN              1150
#define IDC_RADIO_EXPORTFORMAT_SCANDOAS 1151
#define IDC_EDIT_MOTORSTEPSCOMP2        1152
#define IDC_BUTTON4                     1153
#define IDC_BTN_RESETDELETION           1153
#define IDC_UPDATEFILEBTN               1153
#define IDC_LABEL_VOLCANO               1155
#define IDC_LABEL_SITE                  1156
#define IDC_LABEL_OBSERVATORY           1157
#define IDC_LABEL_FITLOW                1158
#define IDC_LABEL_MINCOLUMN             1158
#define IDC_LABEL_FITHIGH               1159
#define IDC_LABEL_MAXCOLUMN             1159
#define IDC_LABEL_COMPASSDIRECTION      1160
#define IDC_LABEL_OUTPUT_DIRECTORY      1161
#define IDC_LABEL_SYSTEMTILT            1161
#define IDC_LABEL_STARTUP               1162
#define IDC_LABEL_FTP_SERVER_URL        1163
#define IDC_LABEL_FTP_USERNAME          1164
#define IDC_LABEL_FTP_PASSWORD          1165
#define IDC_LABEL_FTP_UPLOAD_SERVER     1166
#define IDC_LABEL_SLEEPFROM             1167
#define IDC_LABEL_SLEEPTO               1168
#define IDC_MASTERFRAME                 1169
#define IDC_LABEL_WINDDIRECTION         1170
#define IDC_LABEL_WINDSPEED             1171
#define IDC_LABEL_PLUMEHEIGHT           1172
#define IDC_LABEL_SCANNERSTATUS         1173
#define IDC_LABEL_EVALSTATUS            1174
#define IDC_LABEL_COLUMN_COLOR          1175
#define IDC_LABEL_PEAK_INTENSITY_COLOR  1176
#define IDC_LABEL_COLUMN_COLOR3         1177
#define IDC_LABEL_FIT_INTENSITY_COLOR   1177
#define IDC_RADIO_SERIAL                1181
#define IDC_RADIO_FTP                   1182
#define IDC_FTP_IPADDRESS               1183
#define IDC_RADIO_FREEWAVE_SERIAL       1184
#define IDC_LABEL1                      1189
#define IDC_LABEL2                      1190
#define IDC_LABEL3                      1191
#define IDC_LABEL4                      1192
#define IDC_LABEL5                      1193
#define IDC_LABEL_RADIOID               1194
#define IDC_STATIC_SPECTRA              1195
#define IDC_BROWSE_SPECTRA_BTN          1196
#define IDC_RADIO1                      1197
#define IDC_RADIO2                      1198
#define IDC_RADIO5                      1199
#define IDC_BROWSE_SPECTRA_BTN2         1199
#define IDC_BROWSE_DIRECTORIES_BTN      1199
#define IDC_BROWSE_OUTPUTDIR            1200
#define IDC_RADIO6                      1200
#define IDC_RADIO_SHOWOPTION4           1200
#define IDC_IMPORT_SPECTRA_BTN          1201
#define IDC_IMPORT_PROGRESSBAR          1203
#define IDC_STATUSLABEL                 1204
#define IDC_RADIO3                      1205
#define IDC_RADIO4                      1206
#define IDC_COMBO_CHANNELS              1206
#define IDC_LEGEND_COLUMN               1207
#define IDC_RADIO_MODEL_SOMETIMES       1207
#define IDC_LEGEND_PEAKINTENSITY        1208
#define IDC_LEGEND_DELTA                1209
#define IDC_LEGEND_CHISQUARE            1210
#define IDC_STATIC_PEAKINTENSITY        1211
#define IDC_STATIC_DELTA                1212
#define IDC_STATIC_CHISQUARE            1213
#define IDC_LEGEND_COLUMNERROR          1214
#define IDC_RADIO_SHIFT_FREE            1214
#define IDC_RADIO_SHIFT_FIX             1215
#define IDC_LEGEND_FITINTENSITY         1215
#define IDC_RADIO_SQUEEZE_FREE          1216
#define IDC_STATIC_FITINTENSITY         1216
#define IDC_RADIO_SQUEEZE_FIX           1217
#define IDC_RADIO_SHIFT_LINK            1218
#define IDC_RADIO_SQUEEZE_LINK          1219
#define IDC_LABEL_SPECIE                1220
#define IDC_LABEL_PATH                  1221
#define IDC_FILE_TREE                   1222
#define IDC_RADIO_SHIFT_LIMIT           1222
#define IDC_BROWSE_BUTTON               1223
#define IDC_RADIO_SQUEEZE_LIMIT         1223
#define IDC_EDIT3                       1224
#define IDC_STATUS_MSG                  1224
#define IDC_EDIT_SHIFT_LOWLIMIT         1224
#define IDC_EDIT_SHELL_EXCECUTE         1224
#define IDC_EDIT_CHANNEL                1224
#define IDC_EDIT_SHIFT_HIGHLIMIT        1225
#define IDC_EDIT_SHELL_EXCECUTE_PICTURE 1225
#define IDC_EDIT_SHELL_EXCECUTE_IMAGE   1225
#define IDC_EDIT_SERIAL                 1225
#define IDC_EDIT_SQUEEZE_LOWLIMIT       1226
#define IDC_EDIT_EXPOSURENUM            1226
#define IDC_EDIT_SQUEEZE_HIGHLIMIT      1227
#define IDC_CHECK_AVERAGEDSPECTRA       1227
#define IDC_LEGEND_STARTTIME            1228
#define IDC_LABEL_EVALLOG               1229
#define IDC_MAP_FRAME                   1230
#define IDC_COLUMN_FRAME                1231
#define IDC_RESULT_FRAME                1232
#define IDC_LABEL_VOLCANODISTANCE       1233
#define IDC_LABEL_PAKFILES              1234
#define IDC_LABEL_VOLCANODISTANCE2      1234
#define IDC_BTN_SPLITPAKFILES           1235
#define IDC_PROGRESS_BAR                1236
#define IDC_SCAN_SPIN                   1237
#define IDC_LABEL_SCANNUMBER            1238
#define IDC_LABEL_SCANTIME              1239
#define IDC_RADIO_SHOW_CORR             1240
#define IDC_PLUME_LABEL                 1241
#define IDC_LABEL_PLUME_INFO            1241
#define IDC_LEGEND_SERIES1              1242
#define IDC_LABEL_SERIES1               1243
#define IDC_LEGEND_SERIES2              1244
#define IDC_LABEL_SERIES2               1245
#define IDC_CHECK_SHOW_SUNDIRECTION     1246
#define IDC_LABEL_SZA                   1247
#define IDC_LABEL_SAZ                   1248
#define IDC_COMBO3                      1249
#define IDC_CONFINFO_SITE_LABEL         1250
#define IDC_CONFINFO_COMPASS_LABEL      1251
#define IDC_CONFINFO_LATITUDE_LABEL     1252
#define IDC_CONFINFO_LONGITUDE_LABEL    1253
#define IDC_CONFINFO_CONEORFLAT_LABEL   1254
#define IDC_SCANINFO_STARTTIME_LABEL    1255
#define IDC_SCANINFO_STOPTIME_LABEL     1256
#define IDC_SCANINFO_EXPTIME_LABEL      1257
#define IDC_SCANINFO_NSPEC_LABEL        1258
#define IDC_SCANINFO_CALC_WD_LABEL      1259
#define IDC_SCANINFO_STARTTIME_LABEL2   1260
#define IDC_SCANINFO_DATE_LABEL         1260
#define IDC_SCANINFO_FRAME              1271
#define IDC_RADIO_LOCALDIRECTORY        1272
#define IDC_RADIO_FTPSERVER             1273
#define IDC_CONFINFO_SERIAL             1274
#define IDC_BTN_MERGEPAKFILES           1275
#define IDC_EDIT_OUTPUTFILE             1276
#define IDC_BTN_BROWSEOUTPUTFILE        1277
#define IDC_RADIO_SORTBYNAME_ASC        1278
#define IDC_RADIO_SORTBYNAME_ASC2       1279
#define IDC_RADIO_SORTBYNAME_DES        1279
#define IDC_CHECK_INTERLACED_SPECTRA    1279
#define IDC_RADIO_MEASURE_DARK          1280
#define IDC_CHANGE_SERIAL               1280
#define IDC_RADIO_MODEL_ALWAYS          1281
#define IDC_AVERAGED_SPECTRA            1281
#define IDC_RADIO_DARK_USER_SUPPLIED    1282
#define IDC_LABEL_MASTER1               1283
#define IDC_CHANGE_EXPOSURENUM          1283
#define IDC_LABEL_MASTER2               1284
#define IDC_LABEL_SLAVE1                1285
#define IDC_LABEL_SLAVE2                1286
#define IDC_LABEL_PAKFILENAME           1287
#define IDC_PROPERTIES_FRAME            1289
#define IDC_SPECTRUM_GRAPH_FRAME        1292
#define IDC_SPECTRUM_TABLE_FRAME        1293
#define IDC_SPIN1                       1295
#define IDC_SPECTRUM_SPINBUTTON         1295
#define IDC_LABEL_MESSAGE               1296
#define IDC_LABEL_DARKOFFSETCORR        1297
#define IDC_STATUS_STATIC               1298
#define IDC_LABEL_ELBOX                 1299
#define IDC_RADIO_DARK_MEASURED         1300
#define IDC_RADIO_DARK_SOMETIMES        1301
#define IDC_RADIO_DARK_MODELLED2        1302
#define IDC_RADIO_DARK_MODELLED         1302
#define IDC_COMBO_OFFSET2               1303
#define IDC_RADIO_CONCATENATE           1306
#define IDC_LABEL_FILEINFO              1307
#define IDC_LABEL_DATEANDTIME           1312
#define IDC_LABEL_DATEANDTIME2          1313
#define IDC_CHECK_POSTFLUXLOGS          1313
#define IDC_LABEL_DATEANDTIME3          1314
#define IDC_FRAME_GRAPH                 1314
#define IDC_RADIO_SHOWOPTION            1315
#define IDC_RADIO_SHOWOPTION2           1316
#define IDC_RADIO_SHOWOPTION3           1317
#define IDC_LABEL_CONEANGLE             1322
#define IDC_LABEL_TILT                  1323
#define IDC_EDIT_WINDFIELDFILE          1324
#define IDC_EDIT_RELOADWINDFIELDFILE    1326
#define IDC_RADIO_ANGLE1                1328
#define IDC_RADIO_ANGLE2                1329
#define IDC_LABEL_DEGREES               1330
#define IDC_LABEL_METERS                1331
#define IDC_CHECK_USE_AUTOMATIC_PLUMEPARAM 1332
#define IDC_RADIO_MODE                  1333
#define IDC_RADIO_MODE1                 1333
#define IDC_LABEL_METERS2               1333
#define IDC_RADIO_MODE2                 1334
#define IDC_EDIT_MOTORSTEPSCOMP1        1336
#define IDC_LABEL_STEPSPERROUND         1336
#define IDC_EDIT4                       1337
#define IDC_EDIT_MOTORPOSITION2         1337
#define IDC_FRAME_DISTANCE              1338
#define IDC_LIST_SPECTROMETERS          1340
#define IDC_BUTTON3                     1341
#define IDC_BUTTON_BROWSE_SOLARSPECTRUM 1341
#define IDC_CHECK2                      1342
#define IDC_CHECK_USE_AUTOMATIC_PLUMEPARAM2 1342
#define IDC_LABEL_SWITCHRANGE           1343
#define IDC_COLUMN_30DAY_FRAME          1345
#define IDC_COLUMN_10DAY_FRAME          1346
#define IDC_STATIC_PLOT_OPTIONS         1347
#define IDC_COLUMN_10DAY_FRAME2         1347
#define IDC_COLUMN_1DAY_FRAME           1347
#define IDC_LABEL_SOLARSPECTRUMPATH     1349
#define ID_CONTROL_START                32771
#define ID_VIEW_PEAKINTENSITY_BD        32779
#define ID_VIEW_FITINTENSITY_BD         32780
#define ID_VIEW_COLUMNERROR_BD          32781
#define ID_VIEW_DELTA_BD                32782
#define ID_VIEW_CHISQUARE_BD            32783
#define ID_Menu32784                    32784
#define ID_HISTORY                      32785
#define ID_ANALYSIS_COLUMN_HISTORY      32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1350
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
