/******************************************************************************
*
* (c) 2004 by BECK IPC GmbH
*
*******************************************************************************
*
* Module:    ascii.h
* Function:  ASCII control chars
*
*******************************************************************************
*
* $Header: ASCII.H, 2, 30.08.2005 12:10:56, Andre Pribil$
*
******************************************************************************/


/* ascii control chars */
#define SOH      0x01	//start of heading
#define STX      0x02	//start of text
#define ETX      0x03	//end of text
#define EOT      0x04	//end of transmission
#define ENQ      0x05	//enquity
#define ACK      0x06	//acknowledgement
#define BS       0x08	//backspace
#define CR       0x0d	//carriage return
#define LF       0x0a	//line feed
#define DLE      0x10	//data link escape
#define XON      0x11	//
#define XOFF     0x13
#define NAK      0x15	//negative acknowledgement
#define CAN      0x18	//cancel
#define CTLZ     0x1a
#define ESC      0x1b	//escape
#define NUL      0x00   //NULL

